/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package G2M3E1.Reto05.RedFlix.vista;

import G2M3E1.Reto05.RedFlix.RedFlixApplication;

/**
 *
 * @author Norberto
 */
public class MainFrame extends javax.swing.JFrame {
    
    UsuarioPanel usrPnl;
    PeliculaPanel pelPnl;
    SeriePanel serPnl;

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();        
        
        String [] args = {};
        RedFlixApplication.runSpringServer(args);
        
        pelPnl = new PeliculaPanel();
        usrPnl = new UsuarioPanel();
        serPnl = new SeriePanel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usuarioJBtn = new javax.swing.JButton();
        peliculaJBtn = new javax.swing.JButton();
        serieJBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        limpiarJBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RedFlix");

        usuarioJBtn.setText("Usuario");
        usuarioJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioJBtnActionPerformed(evt);
            }
        });

        peliculaJBtn.setText("Película");
        peliculaJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peliculaJBtnActionPerformed(evt);
            }
        });

        serieJBtn.setText("Serie");
        serieJBtn.setToolTipText("");
        serieJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serieJBtnActionPerformed(evt);
            }
        });

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        limpiarJBtn.setText("Limpiar");
        limpiarJBtn.setToolTipText("");
        limpiarJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarJBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(usuarioJBtn)
                        .addGap(71, 71, 71)
                        .addComponent(peliculaJBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                        .addComponent(serieJBtn)
                        .addGap(71, 71, 71)
                        .addComponent(limpiarJBtn)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usuarioJBtn)
                    .addComponent(serieJBtn)
                    .addComponent(peliculaJBtn)
                    .addComponent(limpiarJBtn))
                .addGap(35, 35, 35)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usuarioJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioJBtnActionPerformed
        usuarioJBtn.setEnabled(false);
        peliculaJBtn.setEnabled(true);
        serieJBtn.setEnabled(true);
        usrPnl.limpiarCampos();
        jPanel1.setVisible(false);
        jPanel1.removeAll();
        jPanel1.add(usrPnl);
        jPanel1.setVisible(true);
    }//GEN-LAST:event_usuarioJBtnActionPerformed

    private void peliculaJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peliculaJBtnActionPerformed
        usuarioJBtn.setEnabled(true);
        peliculaJBtn.setEnabled(false);
        serieJBtn.setEnabled(true);
        pelPnl.limpiarCampos();
        jPanel1.setVisible(false);
        jPanel1.removeAll();
        jPanel1.add(pelPnl);
        jPanel1.setVisible(true);
    }//GEN-LAST:event_peliculaJBtnActionPerformed

    private void serieJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serieJBtnActionPerformed
        usuarioJBtn.setEnabled(true);
        peliculaJBtn.setEnabled(true);
        serieJBtn.setEnabled(false);
        serPnl.limpiarCampos();
        jPanel1.setVisible(false);
        jPanel1.removeAll();
        jPanel1.add(serPnl);
        jPanel1.setVisible(true);
    }//GEN-LAST:event_serieJBtnActionPerformed

    private void limpiarJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarJBtnActionPerformed
        usuarioJBtn.setEnabled(true);
        peliculaJBtn.setEnabled(true);
        serieJBtn.setEnabled(true);
        jPanel1.setVisible(false);
        jPanel1.removeAll();
        jPanel1.setVisible(true);
    }//GEN-LAST:event_limpiarJBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    //public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton limpiarJBtn;
    private javax.swing.JButton peliculaJBtn;
    private javax.swing.JButton serieJBtn;
    private javax.swing.JButton usuarioJBtn;
    // End of variables declaration//GEN-END:variables
}
